name: smp
depend: [EntitySize]
version: '1.9.8'
main: com.smp.Smp
api-version: '1.21'
authors: [ _Noctify ]
commands:
  creload:
    description: Reloads the plugin configuration.
  cgive:
    description: Gives a custom item to the player.
  nv:
    description: Toggles night vision.
    usage: /nv
    permission: smp.nightvision
  nightvision:
    description: Toggles night vision.
    usage: /nightvision
    permission: smp.nightvision
permissions:
  smp.nightvision:
    description: Allows the player to toggle night vision.
    default: true