name: smp
depend: [EntitySize]
version: '1.9.8'
main: com.smp.Smp
api-version: '1.21'
authors: [ _Noctify ]
commands:
  creload:
    description: Reloads the plugin configuration.
  cgive:
    description: Gives a custom item to the player.